"""create product_images table

Revision ID: 485856233496
Revises: 9b92e3bfa924
Create Date: 2026-08-23 11:16:52.900109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485856233496'
down_revision: Union[str, Sequence[str], None] = '9b92e3bfa924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_product_cover', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_cover = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_cover', table_name='product_images', postgresql_where=sa.text('is_cover = true'))
    op.drop_table('product_images')
    # ### end Alembic commands ###
