"""change image url field to TEXT

Revision ID: 73b6e17de24c
Revises: 7f6c4915b21d
Create Date: 2026-08-30 18:37:59.274647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b6e17de24c'
down_revision: Union[str, Sequence[str], None] = '7f6c4915b21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'url',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
